Repository Khayendi/Sys_Dev-with-Okoth, pull requests merged in 2022-12, with the labels that each got.

#1 Roze dev
  app/build.gradle
  app/src/main/java/com/code/tusome/db/TusomeDB.kt
  app/src/main/java/com/code/tusome/db/TusomeDao.kt
  app/src/main/java/com/code/tusome/models/Assignment.kt
  app/src/main/java/com/code/tusome/models/User.kt
  app/src/main/java/com/code/tusome/ui/fragments/AssignmentsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/auth/frags/LoginFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/auth/frags/SignUpFragment.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/MainViewModel.kt
  app/src/main/res/layout/fragment_assignments.xml
  docs/~$SOME One pager.docx
Labels: enhancement

#3 Working on the viewmodel
  .idea/gradle.xml
  .idea/misc.xml
  README.md
  app/src/main/java/com/code/tusome/models/Assignment.kt
  app/src/main/java/com/code/tusome/models/Course.kt
  app/src/main/java/com/code/tusome/models/User.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/MainViewModel.kt
Labels: enhancement

#4 Jamie dev
  .idea/gradle.xml
  .idea/misc.xml
  README.md
  app/src/main/java/com/code/tusome/models/Assignment.kt
  app/src/main/java/com/code/tusome/models/Course.kt
  app/src/main/java/com/code/tusome/models/User.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/MainViewModel.kt
Labels: enhancement

#5 Dev
  README.md
Labels: enhancement

#6 Updated One Pager
  docs/TUSOME One pager.docx
Labels: documentation

#8 Create tusome_unit_test.yml
  .github/workflows/tusome_unit_test.yml
Labels: documentation, enhancement

#12 Update
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/code/tusome/models/Course.kt
  app/src/main/java/com/code/tusome/ui/activities/HomeActivity.kt
  app/src/main/java/com/code/tusome/ui/fragments/AddAssignmentFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/AddCatFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/AddExamFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/AssignmentsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/ResultsFragment.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/AssignmentViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/CatsViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/ExamViewModel.kt
  app/src/main/res/layout/fragment_add_assignment.xml
  app/src/main/res/layout/fragment_add_cat.xml
  app/src/main/res/layout/fragment_add_exam.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/menu/admin_menu.xml
  app/src/main/res/navigation/admin_menu_nav.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#13 Changes
  app/src/main/java/com/code/tusome/ui/fragments/CatsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/ExamFragment.kt
Labels: enhancement

#14 Updating master
  app/src/main/java/com/code/tusome/ui/fragments/CatsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/ExamFragment.kt
Labels: enhancement

#15 Small changes
  app/src/main/java/com/code/tusome/db/TusomeDao.kt
  app/src/main/java/com/code/tusome/models/Course.kt
Labels: enhancement

#16 Updating
  app/src/main/java/com/code/tusome/db/TusomeDao.kt
  app/src/main/java/com/code/tusome/models/Course.kt
Labels: enhancement

#19 Added more refactored code
  app/src/main/java/com/code/tusome/ui/fragments/AddAssignmentFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/AddCatFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/AddExamFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/AssignmentsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/CatsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/ExamFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/auth/frags/SignUpFragment.kt
  app/src/main/res/layout/fragment_assignments.xml
  app/src/main/res/layout/fragment_cats.xml
  app/src/main/res/layout/fragment_courses.xml
  app/src/main/res/layout/fragment_exam.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#20 Dev
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  app/src/main/java/com/code/tusome/adapters/AssignmentsAdapter.kt
  app/src/main/java/com/code/tusome/adapters/CatsAdapter.kt
  app/src/main/java/com/code/tusome/adapters/CourseAdapter.kt
  app/src/main/java/com/code/tusome/adapters/ExamsAdapter.kt
  app/src/main/java/com/code/tusome/adapters/UnitsAdapter.kt
  app/src/main/java/com/code/tusome/models/User.kt
  app/src/main/java/com/code/tusome/ui/fragments/AddAssignmentFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/AddCatFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/AddExamFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/AssignmentsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/CatsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/CoursesFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/ExamFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/UnitsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/auth/frags/LoginFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/auth/frags/SignUpFragment.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/AssignmentViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/MainViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/UnitsViewModel.kt
  app/src/main/java/com/code/tusome/utils/Utils.kt
  app/src/main/res/layout/fragment_add_assignment.xml
  app/src/main/res/layout/fragment_add_cat.xml
  app/src/main/res/layout/fragment_add_exam.xml
  app/src/main/res/layout/fragment_assignment.xml
  app/src/main/res/layout/fragment_assignments.xml
  app/src/main/res/layout/fragment_cats.xml
  app/src/main/res/layout/fragment_courses.xml
  app/src/main/res/layout/fragment_exam.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#29 Jamie dev
  app/src/main/java/com/code/tusome/ui/viewmodels/AssignmentViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/CatsViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/CourseViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/ExamViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/MainViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/UnitsViewModel.kt
  app/src/test/java/com/code/tusome/ui/viewmodels/CatsViewModelTest.kt
Labels: enhancement

#28 Jamie dev
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/androidTest/java/com/code/tusome/ui/fragments/SplashFragmentTest.kt
  app/src/main/java/com/code/tusome/Calculator.kt
  app/src/main/java/com/code/tusome/adapters/AssignmentsAdapter.kt
  app/src/main/java/com/code/tusome/adapters/CatsAdapter.kt
  app/src/main/java/com/code/tusome/adapters/CourseAdapter.kt
  app/src/main/java/com/code/tusome/adapters/ExamsAdapter.kt
  app/src/main/java/com/code/tusome/adapters/UnitsAdapter.kt
  app/src/main/java/com/code/tusome/ui/fragments/AssignmentsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/CatsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/CoursesFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/ExamFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/SplashFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/UnitsFragment.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/AssignmentViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/CatsViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/CourseViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/ExamViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/MainViewModel.kt
  app/src/main/java/com/code/tusome/ui/viewmodels/UnitsViewModel.kt
  app/src/main/res/layout/fragment_assignments.xml
  app/src/test/java/com/code/tusome/CalculatorTest.kt
  app/src/test/java/com/code/tusome/ui/viewmodels/CatsViewModelTest.kt
Labels: duplicate

#30 Jamie dev
  app/src/main/java/com/code/tusome/adapters/UnitsAdapter.kt
  app/src/main/java/com/code/tusome/models/Course.kt
  app/src/main/java/com/code/tusome/ui/fragments/AddUnitFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/AssignmentsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/CatsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/CoursesFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/ExamFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/UnitsFragment.kt
  app/src/main/java/com/code/tusome/ui/fragments/auth/frags/SignUpFragment.kt
  app/src/main/res/layout/fragment_assignments.xml
  app/src/main/res/layout/fragment_courses.xml
Labels: documentation
